S_CREATE_LOBBY = 41
S_JOIN_LOBBBY = 42
S_LEAVE_LOBBY = 43
S_START_GAME = 50
S_SCREENSHOT_TAKEN = 120
S_PLAYER_INPUT = 60

C_JOINED_LOBBY = 32
C_LOBBY_ALREADY_EXISTS = 33
C_LOBBY_DOESNT_EXISTS = 34
C_NOT_JOIN = 35
C_LEAVE_LOBBY = 36
C_LOBBY_DATA = 40
C_GAME_STARTED = 45
C_GAME_DATA = 50